<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(SpineMauiTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Plugin.Maui.Spine</AssemblyName>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="WinUIEx" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Plugin.Maui.Spine.Svg\Plugin.Maui.Spine.Svg.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="Platforms\iOS\" />
    <Folder Include="Platforms\MacCatalyst\" />
  </ItemGroup>

	<ItemGroup>
		<None Include="build\**" Pack="true" PackagePath="build\;buildTransitive\;" />
	</ItemGroup>

</Project>
