<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>Plugin.Maui.Spine.Common</AssemblyName>
		<RootNamespace>Plugin.Maui.Spine.Common</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

</Project>
